### ISSUE TITLE
Feature: WorkflowClient 

### ISSUE THREAD

**Issue by wh1337** [novuhq/novu-dotnet#19]
Implement all endpoint methods for the notification endpoints. 

Documentation for the endpoints can be found here: https://docs.novu.co/api/get-notifications/

### Endpoints
- [ ] Get notifications
- [ ] Get notification statistics
- [ ] Get notification graph statistics
- [ ] Get notification

**Comment by Badabum** [comment]
@wh1337 I can pick this

**Comment by unicodeveloper** [comment]
@Badabum Has this been worked on yet?

**Comment by toddb** [comment]
Released as part of 0.3.0
