### ISSUE TITLE
Feature: IntegrationClient

### ISSUE THREAD

**Issue by wh1337** [novuhq/novu-dotnet#20]
Implement all endpoint methods for the Integration endpoints.

Documentation for the endpoints can be found here: https://docs.novu.co/api/get-integrations/

## Endpoints

- [ ] Get integrations
- [ ] Create integration
- [ ] Get active integrations
- [ ] Get webhook support status for provider
- [ ] Update integration
- [ ] Delete integration

**Comment by unicodeveloper** [comment]
Any update here? @wh1337 @badabum

**Comment by Alabuja** [comment]
> Any update here? @wh1337 @badabum

Hi @unicodeveloper , please what's the status of this so that I can start working on it?

**Comment by Alabuja** [comment]
Hi @wh1337, please from the readme.md file, the project structure says it's meant to contain clients and utilities folder but I cant find any. Also, the Contributing file looks like a set-up for JavaScript.  Thank you.

**Comment by Alabuja** [comment]
Hi @wh1337 @unicodeveloper , please i've still not heard from you concerning what was noticed above. Thank you & I looking forward to hearing from you.

**Comment by Alabuja** [comment]
Hi @wh1337, please I'm still yet to see the update on that. Thank you.

**Comment by toddb** [comment]
Released as part of 0.3.0
