### ISSUE TITLE
Feature: LayoutClient

### ISSUE THREAD

**Issue by wh1337** [novuhq/novu-dotnet#21]
Implement all endpoint methods for the Layout endpoints.

Documentation for the endpoints can be found here: https://docs.novu.co/api/layout-creation/

## Endpoints

- [ ] Layout creation
- [ ] Filter layouts
- [ ] Get layout
- [ ] Delete layout
- [ ] Update layout
- [ ] Set default layout

**Comment by J-rayX** [comment]
Hi @wh1337,

What are the instructions to set up the project in one's local environment? The CONTRIBUTING guide looks like it'd work for JavaScript-based projects.

Then, the README mentions the `Clients` directory containing the implementation of API calls. But, the folder is missing in the repo. Was it intentionally omitted or was the design of the project changed?
There's a `NovuClient.cs` file however.

Cc: @unicodeveloper

**Comment by J-rayX** [comment]
> Hey @J-rayX, apologies about that. I will be getting those documents updated hopefully by the end of tonight. 

Alright. I'll eagerly await that. Thanks.

**Comment by toddb** [comment]
Released as part of 0.3.0
