### ISSUE TITLE
Feature: NotificationTemplateClient

### ISSUE THREAD

**Issue by wh1337** [novuhq/novu-dotnet#22]
Implement all endpoint methods for the Notification Template endpoints.

Documentation for the endpoints can be found here: https://docs.novu.co/api/get-notification-templates/

## Endpoints

- [ ] Get notification templates
- [ ] Get notification template
- [ ] Update notification template
- [ ] Delete notification template
- [ ] Update notification template status

**Comment by unicodeveloper** [comment]
@Badabum are you open to taking up this issue? We'll like to get it in this week.

**Comment by Badabum** [comment]
Hey, not sure yet. But prob will have some time tomorrow and Thursday to work on it.

**Comment by Badabum** [comment]
PR for basic operations is [here](https://github.com/novuhq/novu-dotnet/pull/30)

**Comment by Badabum** [comment]
@wh1337 can you share somehow output of failed tests?
