### ISSUE TITLE
Feature: WorkflowGroupClient

### ISSUE THREAD

**Issue by wh1337** [novuhq/novu-dotnet#23]
Implement all endpoint methods for the Workflow Group endpoints.

Documentation for the endpoints can be found here: https://docs.novu.co/api/create-notification-group/

## Endpoints

- [ ] Create workflow group
- [ ] Get workflow groups

**Comment by unicodeveloper** [comment]
@wh1337 @badabum Any update here?

**Comment by RaphaelNagato** [comment]
@wh1337 , The link to the docs is broken

![image](https://github.com/novuhq/novu-dotnet/assets/37874789/bae0a028-8252-4e6f-a963-0a61cb1c34f6)

**Comment by unicodeveloper** [comment]
Sorry about that. Notifications has been renamed to Workflow. It is now called Workflow Groups.

This is the URL: https://docs.novu.co/api/create-workflow-group/

**Comment by RaphaelNagato** [comment]
Hello @unicodeveloper, @wh1337,  is anyone working on this at the moment and if not,  can I start working on it?

**Comment by unicodeveloper** [comment]
I have assigned the issue to you. Thanks for picking this up 🙏🏿

**Comment by RaphaelNagato** [comment]
Hi @wh1337 , @unicodeveloper , can you review your PR to implement this feature? Thanks

**Comment by unicodeveloper** [comment]
@wh1337 Will review today or tomorrow. Thanks for sending this in.
