### ISSUE TITLE
Use client code generation from novu open api specification

### ISSUE THREAD

**Issue by Badabum** [novuhq/novu-dotnet#31]
Hi all, 
Since novu has openapi specification, we can use a tool like [Kiota](https://learn.microsoft.com/en-us/openapi/kiota/overview) to automatically generate client that can be used to call the api. This will significantly reduce the time to build SDK that has full coverage of the available Novu API.
The only downside is that this will force us to rely on opinionated way to structure client and endpoints and how SDK client consume it. Though generated part can be made "internal" and public api will be handwritten on top of it.

Example sdk project structure is we will use client generation:
![image](https://github.com/novuhq/novu-dotnet/assets/6359085/1438e3eb-21d6-4306-b886-f593a8cfb9fa)

Example of generated client usage:
![image](https://github.com/novuhq/novu-dotnet/assets/6359085/97600897-76e8-404d-9488-fff968311735)

This generated client can be made internal and then we can build our own public contract on top of it. For example:
![image](https://github.com/novuhq/novu-dotnet/assets/6359085/b819946e-8d7e-455f-a2b9-d398189e1a3e)

**Comment by unicodeveloper** [comment]
We don't want to automatically generate any client SDK. We followed this route because we want an active community of contributors and also not to be confined to third-party tools @Badabum

**Comment by Badabum** [comment]
@unicodeveloper alright.
