### ISSUE TITLE
Update tests to remove the dependency on a real connection to api.novu.co

### ISSUE THREAD

**Issue by wh1337** [novuhq/novu-dotnet#34]
Currently, when the test run they require a real connection to the `api.novu.co`. We need to refactor this to use a mock api so that tests from external PRs can run. This also follows the normal testing process.

**Comment by RaphaelNagato** [comment]
Hi @wh1337, I will like to pick this up once my PR to add the WorkflowClient is resolved. Thanks

**Comment by RaphaelNagato** [comment]
Hi @wh1337 , I plan to use Wiremock.Net library to resolve this issue, is it okay by you?

**Comment by toddb** [comment]
Released as part of 0.3.0. However, please note that the additional code to help streamline wiring up the configuration exists in [Novu.Extensions](https://github.com/novuhq/novu-dotnet/tree/main/src/Novu.Extensions).

See #55 for discussion and this code should be release soon.
