### ISSUE TITLE
Setup GitHub Workflow for Running Unit Tests

### ISSUE THREAD

**Issue by Cliftonz** [novuhq/novu-dotnet#73]
In order to ensure the stability and reliability of our codebase, it is essential to have automated unit tests running for each push and pull request. Currently, our repository lacks a GitHub Actions workflow to run unit tests, and this needs to be addressed to maintain code quality and catch issues early.

Suggested Solution:

 1.   Create a new workflow file in .github/workflows/ directory.
        Filename: run-unit-tests.yml

2.    Configure the workflow to be triggered on every push and pull_request event to the main branch.
3.    Define job steps:
        Checkout the repository.
        Setup the environment/java runtime.
        Install dependencies.
        Run the unit tests.

**Comment by Smartmind12** [comment]
@Cliftonz Can i work on this issue as a part of Hacktoberfest?

**Comment by Cliftonz** [comment]
Of course, let us know if you hit any issues.

**Comment by toddb** [comment]
@wh1337 please weigh in here if you know better

@Cliftonz We already have `https://github.com/novuhq/novu-dotnet/blob/main/.github/workflows/dotnet-test.yaml`, what is the problem? 

It gets run before a release (ie on a merge) AFAIK.

**Comment by unicodeveloper** [comment]
I'd like to add to the discussion here. @Cliftonz has been raising concerns on other repositories due to the absence of unit test workflows. 

I believe this may have been an oversight, assuming this repository lacked such setups, when it's actually already in place. And we can probably just keep tweaking the workflows.

**Comment by unicodeveloper** [comment]
So, I'll just close this issue. @Smartmind12 sorry for the confusion. Feel free to pick from other existing issues.

**Comment by Smartmind12** [comment]
> So, I'll just close this issue. @Smartmind12 sorry for the confusion. Feel free to pick from other existing issues.

No worries i understand and surely will work on the issue that i have raised…Thanks!
