### ISSUE TITLE
Did not found EventTriggerDataDto

### ISSUE THREAD

**Issue by uzzaircuremd** [novuhq/novu-dotnet#74]

**Comment by uzzaircuremd** [comment]
I di not found EventTriggerDataDto in C# std. while its mention in code suggestion.

![image](https://github.com/novuhq/novu-dotnet/assets/146197938/d06627f4-66bf-408f-828f-a27391f1e7ce)

**Comment by toddb** [comment]
That documentation does not belong to this repository and is the documentation for Novu itself (and is outdated although in issue #72  you can see the authors are trying to get up to date). 

`EvenTriggerDataDto` is obsolete as of 0.3.0 of this library and the documentation on the [readme)](https://github.com/novuhq/novu-dotnet/blob/main/README.md?plain=1#L111) has the new implementation which I will repeat:

```
await Event.Trigger(
            new EventCreateData
            {
                EventName = 'event-name',
                To = { SubscriberId =subscriberId },
                Payload = new Payload("Bogus payload"),
            });
```
